name: iux_flutter
description: Human-centred foundations and UX patterns for Flutter applications.
version: 0.1.0-dev.4
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
